/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerIndexRouteImport } from './routes/career.index'
import { Route as CareerCreateRouteImport } from './routes/career.create'
import { Route as CareerCalendarRouteImport } from './routes/career.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/career/',
  path: '/career/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCreateRoute = CareerCreateRouteImport.update({
  id: '/career/create',
  path: '/career/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCalendarRoute = CareerCalendarRouteImport.update({
  id: '/career/calendar',
  path: '/career/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career/calendar': typeof CareerCalendarRoute
  '/career/create': typeof CareerCreateRoute
  '/career/': typeof CareerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career/calendar': typeof CareerCalendarRoute
  '/career/create': typeof CareerCreateRoute
  '/career': typeof CareerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career/calendar': typeof CareerCalendarRoute
  '/career/create': typeof CareerCreateRoute
  '/career/': typeof CareerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/career/calendar' | '/career/create' | '/career/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/career/calendar' | '/career/create' | '/career'
  id: '__root__' | '/' | '/career/calendar' | '/career/create' | '/career/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerCalendarRoute: typeof CareerCalendarRoute
  CareerCreateRoute: typeof CareerCreateRoute
  CareerIndexRoute: typeof CareerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/': {
      id: '/career/'
      path: '/career'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/create': {
      id: '/career/create'
      path: '/career/create'
      fullPath: '/career/create'
      preLoaderRoute: typeof CareerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career/calendar': {
      id: '/career/calendar'
      path: '/career/calendar'
      fullPath: '/career/calendar'
      preLoaderRoute: typeof CareerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerCalendarRoute: CareerCalendarRoute,
  CareerCreateRoute: CareerCreateRoute,
  CareerIndexRoute: CareerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
